import type { ProductImageScene, CategoryCollection, ProductCategory } from './types';

export const GLOBAL_SCENES: ProductImageScene[] = [
  {
    id: 'clean-packshot',
    title: 'Clean Studio Shot',
    description: 'Pure white background cut-out. For clothing: ghost mannequin or flat-lay. For accessories and products: standard packshot.',
    promptTemplate: '{{categoryPackshotDirective}} Professional ecommerce product photograph of {{productName}} ({{productType}}) on {{background}} seamless background. {{lightingDirective}} Sharp center-frame composition with crisp product edges. Ultra-sharp focus on every surface detail — {{materialTexture}}, label text, finish reflections. True-to-life color accuracy, {{shadowDirective}} {{compositionDirective}} {{negativeSpaceDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background', 'productSize'],
    isGlobal: true,
    sceneType: 'packshot',
  },
  {
    id: 'marketplace-ready',
    title: 'Marketplace Listing',
    description: 'Optimized for Amazon, Etsy, Shopify storefronts.',
    promptTemplate: 'Clean ecommerce listing photograph of {{productName}} ({{productType}}) on pure seamless white background. Perfectly centered, no clipping at edges. {{lightingDirective}} True-to-life color with no color cast. {{shadowDirective}} Sharp focus across entire product — {{materialTexture}}. Optimized for marketplace thumbnail clarity. {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background'],
    isGlobal: true,
    sceneType: 'packshot',
  },
  {
    id: 'editorial-surface',
    title: 'Editorial on Surface',
    description: 'Product on a premium styled surface with editorial mood.',
    promptTemplate: 'Editorial product photograph of {{productName}} {{surfaceDirective}}. {{lightingDirective}} {{moodDirective}} {{sceneIntensityDirective}} {{productProminenceDirective}} Rich textural interplay between product ({{materialTexture}}) and surface material. Shallow depth of field with tack-sharp focus on the product. {{stylingDirective}} {{accentDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['visualDirection', 'sceneEnvironment'],
    isGlobal: true,
    sceneType: 'editorial',
  },
  {
    id: 'product-pedestal',
    title: 'Product on Pedestal',
    description: 'Elevated on a block, plinth, or sculptural display base.',
    promptTemplate: 'Premium product photograph of {{productName}} elevated on a sculptural display pedestal. {{lightingDirective}} Eye-level to slightly low camera angle emphasizing product stature. {{shadowDirective}} Crisp focus on {{materialTexture}} with clean pedestal edges. {{moodDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background', 'visualDirection'],
    isGlobal: true,
    sceneType: 'packshot',
  },
  {
    id: 'tabletop-lifestyle',
    title: 'Tabletop Lifestyle',
    description: 'Product styled on a table in a natural setting.',
    promptTemplate: 'Lifestyle product photograph of {{productName}} styled on a natural table surface. {{environmentDirective}} {{lightingDirective}} Product is hero — sharp focus on {{materialTexture}} with contextual props slightly blurred. {{surfaceDirective}} Believable, lived-in styling with clean composition. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['sceneEnvironment', 'productSize'],
    isGlobal: true,
    sceneType: 'lifestyle',
  },
  {
    id: 'in-hand-studio',
    title: 'In-Hand Studio',
    description: 'Hand holding product in clean studio setting.',
    promptTemplate: 'Studio product photograph of {{productName}} held in a {{handStyle}} hand against a {{background}} background. {{personDirective}} Crisp edge-to-edge sharpness on both product and skin — visible skin pores, natural hand anatomy, {{nailDirective}}. {{lightingDirective}} Product is the clear hero, hand provides natural scale and context. {{materialTexture}}. {{actionDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['personDetails', 'actionDetails', 'productSize'],
    isGlobal: true,
    sceneType: 'portrait',
    excludeCategories: ['home-decor', 'tech-devices'],
  },
  {
    id: 'in-hand-lifestyle',
    title: 'In-Hand Lifestyle',
    description: 'Product held naturally in a real-world context.',
    promptTemplate: 'Lifestyle photograph of {{productName}} held naturally in a real-world setting. {{personDirective}} {{environmentDirective}} Natural grip showing {{handStyle}} hand with {{nailDirective}}. Hyper-realistic skin texture with visible pores. {{lightingDirective}} Product remains sharp hero — {{materialTexture}}. Background softly blurred for depth. {{actionDirective}} {{outfitDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['personDetails', 'actionDetails', 'sceneEnvironment', 'productSize'],
    isGlobal: true,
    sceneType: 'lifestyle',
    excludeCategories: ['home-decor', 'tech-devices'],
  },
  {
    id: 'closeup-detail',
    title: 'Close-Up Detail',
    description: 'Tight crop highlighting product details and finish.',
    promptTemplate: 'Extreme close-up macro photograph of {{productName}} construction details. Tack-sharp focus on {{focusArea}} — visible micro-details: {{materialTexture}}, edge finishing, surface imperfections that prove authenticity. {{cropDirective}} Shallow depth of field with creamy bokeh. {{lightingDirective}} {{brandingDirective}} {{cameraDirective}}',
    triggerBlocks: ['detailFocus'],
    isGlobal: true,
    sceneType: 'macro',
  },
  {
    id: 'side-profile',
    title: 'Side Profile',
    description: 'Product from 90° side angle showing depth and construction.',
    promptTemplate: 'Product photograph of {{productName}} from a 90-degree side angle. {{lightingDirective}} Side view revealing depth, construction, and profile silhouette. {{materialTexture}}. {{shadowDirective}} Clean {{background}} background with sharp product edges. {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background'],
    isGlobal: true,
    sceneType: 'packshot',
  },
  {
    id: 'back-view',
    title: 'Back View',
    description: 'Rear view showing back construction and details.',
    promptTemplate: 'Product photograph of {{productName}} from the back/rear angle. {{lightingDirective}} Showing back construction, label placement, and structural details. {{materialTexture}}. {{shadowDirective}} Clean {{background}} background. {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background'],
    isGlobal: true,
    sceneType: 'packshot',
  },
  {
    id: 'top-down-flatlay',
    title: 'Top-Down / Flat Lay',
    description: 'Overhead bird\'s-eye view of the product.',
    promptTemplate: 'Overhead flat-lay photograph of {{productName}} shot from directly above. {{lightingDirective}} Bird\'s-eye view revealing top surface, shape outline, and footprint. {{materialTexture}}. {{shadowDirective}} Clean {{background}} background. {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background'],
    isGlobal: true,
    sceneType: 'flatlay',
  },
  {
    id: 'product-packaging',
    title: 'Product + Packaging',
    description: 'Product styled together with its box or packaging.',
    promptTemplate: 'Professional photograph of {{productName}} styled with its packaging. {{packagingDirective}} Both product and packaging in sharp focus — {{materialTexture}} on the product, printed details and construction visible on packaging. {{lightingDirective}} {{shadowDirective}} Composition balances product and packaging as co-heroes. {{brandingDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['packagingDetails'],
    isGlobal: true,
    sceneType: 'packshot',
    excludeCategories: ['garments'],
  },
  {
    id: 'packaging-detail',
    title: 'Packaging Detail',
    description: 'Close-up of packaging design, label, or construction.',
    promptTemplate: 'Macro close-up of {{productName}} packaging construction and design. Tack-sharp focus on {{focusArea}} — printed text legibility, material texture of box/carton, edge finishing, embossing or foil detail. {{packagingDirective}} {{lightingDirective}} {{cropDirective}} {{brandingDirective}} {{cameraDirective}}',
    triggerBlocks: ['packagingDetails', 'detailFocus'],
    isGlobal: true,
    sceneType: 'macro',
    excludeCategories: ['garments'],
  },
  {
    id: 'accent-backdrop',
    title: 'Accent Color Backdrop',
    description: 'Product on a dynamic background derived from its dominant color.',
    promptTemplate: 'Product photograph of {{productName}} on a {{accentColorDirective}}. {{lightingDirective}} Sharp center-frame composition with crisp product edges. {{materialTexture}}. {{shadowDirective}} {{consistencyDirective}} {{cameraDirective}}',
    triggerBlocks: ['background'],
    isGlobal: true,
    sceneType: 'packshot',
  },
];

export const CATEGORY_COLLECTIONS: CategoryCollection[] = [
  {
    id: 'fragrance',
    title: 'Fragrance',
    scenes: [
      {
        id: 'fragrance_hero_surface', title: 'Hero Bottle on Stone',
        description: 'Clean hero packshot on a refined surface like stone, plaster, marble, or brushed wood.',
        promptTemplate: 'Luxury fragrance bottle photograph of {{productName}} placed on a natural surface — marble, travertine, or raw plaster slab. {{surfaceDirective}} Eye-level to slightly low angle, shallow depth of field with tack-sharp focus on the bottle. Visible glass refraction, liquid color depth inside bottle, cap material texture ({{materialTexture}}), and label embossing. {{lightingDirective}} Warm ambient fill light. {{moodDirective}} {{accentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'editorial',
      },
      {
        id: 'fragrance_cap_nozzle_detail', title: 'Cap & Atomizer Detail',
        description: 'Close-up of cap, spray nozzle, glass edge, label finish, or reflective hardware.',
        promptTemplate: 'Extreme macro close-up of {{productName}} fragrance bottle details — cap construction, atomizer nozzle mechanism, glass edge thickness, label printing quality. Tack-sharp focus on {{focusArea}}. Visible micro-details: {{materialTexture}}, metal plating finish, glass refraction edges. {{lightingDirective}} Shallow depth of field with creamy background bokeh. {{cropDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'macro',
      },
      {
        id: 'fragrance_shelf_placement', title: 'Shelf Styling Scene',
        description: 'Bottle placed on a shelf, console, or ledge in a calm interior setting.',
        promptTemplate: 'Interior lifestyle photograph of {{productName}} fragrance bottle placed on a styled shelf or console ledge. {{environmentDirective}} {{lightingDirective}} Bottle in sharp focus with {{materialTexture}} clearly visible — glass clarity, liquid color, cap finish. Surrounding decor softly blurred for depth. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'lifestyle',
      },
      {
        id: 'fragrance_in_hand', title: 'Fragrance in Hand',
        description: 'Elegant hand-held composition showing scale and premium feel.',
        promptTemplate: 'Elegant hand-held fragrance photograph — {{productName}} bottle held delicately in a {{handStyle}} hand. {{personDirective}} Visible skin pores and natural hand anatomy, {{nailDirective}}. Glass bottle showing refraction and liquid depth, {{materialTexture}}. {{lightingDirective}} Product is clear hero with hand providing luxurious scale context. {{outfitDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'portrait',
      },
      {
        id: 'fragrance_product_packaging', title: 'Bottle & Box Composition',
        description: 'Bottle styled with outer packaging for launch visuals or gifting.',
        promptTemplate: 'Launch-ready composition of {{productName}} fragrance bottle alongside its outer box packaging. {{packagingDirective}} Both in sharp focus — glass refraction and liquid depth on bottle, printed detail and construction quality on box. {{lightingDirective}} {{shadowDirective}} {{brandingDirective}} Luxurious gifting composition. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['packagingDetails'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'packshot',
      },
      {
        id: 'fragrance_vanity_editorial', title: 'Vanity Ritual Scene',
        description: 'Fragrance in a dressing-table or vanity setting with mirrors and soft reflections.',
        promptTemplate: 'Editorial vanity scene — {{productName}} fragrance on a dressing table with mirror reflections and soft ambient light. {{environmentDirective}} Glass bottle catching mirror reflections, {{materialTexture}}. {{lightingDirective}} Warm intimate atmosphere with visible perfume ritual context. {{moodDirective}} {{stylingDirective}} {{accentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment', 'visualDirection'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'editorial',
      },
      {
        id: 'fragrance_editorial_still_life', title: 'Atmospheric Still Life',
        description: 'Brand-led composition with shadows, sculptural props, and campaign-style mood.',
        promptTemplate: 'Atmospheric still-life composition featuring {{productName}} fragrance. Campaign-style mood with sculptural shadows and dramatic light play. {{lightingDirective}} {{moodDirective}} Glass refraction and liquid depth clearly visible, {{materialTexture}}. Intentional negative space and strong composition. {{accentDirective}} {{stylingDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'fragrance',
        sceneType: 'editorial',
      },
    ],
  },
  {
    id: 'beauty-skincare',
    title: 'Beauty & Skincare',
    scenes: [
      {
        id: 'beauty_shelf_placement', title: 'Shelf Placement',
        description: 'Product on a shelf in a bathroom, spa, or minimal interior.',
        promptTemplate: 'Interior product photograph of {{productName}} placed on a shelf in a clean bathroom or spa environment. {{environmentDirective}} {{lightingDirective}} Product in sharp focus — {{materialTexture}}, label legibility, dispenser or cap detail. Surrounding context softly blurred. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'lifestyle',
      },
      {
        id: 'beauty_vanity_placement', title: 'Vanity Counter Scene',
        description: 'Product on a sink, vanity counter, or bathroom tray.',
        promptTemplate: 'Beauty counter photograph — {{productName}} placed on a bathroom vanity, sink edge, or marble tray. {{surfaceDirective}} {{lightingDirective}} Crisp product detail — {{materialTexture}}, label text, pump or cap mechanism. Water droplets or dewy textures add freshness. {{moodDirective}} {{environmentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'lifestyle',
      },
      {
        id: 'beauty_texture_formula', title: 'Formula Texture Close-Up',
        description: 'Cream, serum, gel, or lotion in a detailed texture shot.',
        promptTemplate: 'Extreme close-up texture photograph of {{productName}} formula — cream, serum, gel, or lotion shown as a swatch or pour. Tack-sharp focus on {{focusArea}}. {{lightingDirective}} Visible micro-texture that communicates product feel and formula quality. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'macro',
      },
      {
        id: 'beauty_in_hand', title: 'Beauty in Hand',
        description: 'Product held with neat styling and beauty-oriented framing.',
        promptTemplate: 'Beauty hand-held photograph of {{productName}} held in a {{handStyle}} hand. {{personDirective}} {{nailDirective}}. {{lightingDirective}} Product showing {{materialTexture}} — label text, dispenser detail. Beauty-oriented tight framing. {{actionDirective}} {{outfitDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'portrait',
      },
      {
        id: 'beauty_editorial_surface', title: 'Editorial Surface Composition',
        description: 'Product on a premium surface with soft lighting and clean campaign composition.',
        promptTemplate: 'Editorial beauty composition — {{productName}} {{surfaceDirective}}. {{lightingDirective}} Clean campaign-level composition with intentional negative space. {{materialTexture}} rendered with precision. {{moodDirective}} {{accentDirective}} {{stylingDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'editorial',
      },
      {
        id: 'beauty_application_skin', title: 'Application on Skin',
        description: 'Product shown in real use on skin, cheek, hand, or body.',
        promptTemplate: 'Beauty application photograph — {{productName}} being applied on skin (cheek, hand, or décolletage). {{personDirective}} Hyper-realistic skin texture: visible pores, natural skin imperfections, realistic absorption or coverage. {{lightingDirective}} Sharp focus on the application zone with product visible. {{actionDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'portrait',
      },
      {
        id: 'beauty_routine_grouping', title: 'Routine Set Composition',
        description: 'Multiple beauty products arranged in a daily routine format.',
        promptTemplate: 'Beauty routine composition featuring {{productName}} as hero, arranged in a logical skincare/beauty routine sequence. {{surfaceDirective}} {{lightingDirective}} Each product in sharp focus — {{materialTexture}}, label legibility. Clean organized arrangement suggesting daily ritual. {{environmentDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'beauty-skincare',
        sceneType: 'flatlay',
      },
    ],
  },
  {
    id: 'makeup-lipsticks',
    title: 'Makeup & Lipsticks',
    scenes: [
      {
        id: 'makeup_near_lips_closeup', title: 'Product Near Lips',
        description: 'Tight beauty crop where the product sits close to lips or face.',
        promptTemplate: 'Tight beauty close-up — {{productName}} held near the lips or face. {{personDirective}} Hyper-realistic skin texture: visible lip texture, skin pores, natural complexion. Product in tack-sharp focus showing {{materialTexture}}, bullet shape or applicator tip. {{lightingDirective}} Beauty-grade shallow depth of field. {{focusArea}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'detailFocus'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'portrait',
      },
      {
        id: 'makeup_portrait_with_product', title: 'Portrait with Product',
        description: 'Portrait-led shot where the model presents the cosmetic item.',
        promptTemplate: 'Beauty portrait — model presenting {{productName}} cosmetic. {{personDirective}} {{outfitDirective}} Hyper-realistic skin rendering with visible pores, natural complexion, and makeup if applied. Product sharply visible in frame — {{materialTexture}}. {{lightingDirective}} {{moodDirective}} Aspirational beauty composition. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'portrait',
      },
      {
        id: 'makeup_in_hand', title: 'Makeup in Hand',
        description: 'Refined hand-held shot for lipsticks, mascaras, compacts, liners.',
        promptTemplate: 'Refined hand-held beauty photograph — {{productName}} held elegantly in a {{handStyle}} hand. {{personDirective}} Crisp detail on both product ({{materialTexture}}) and skin — visible pores, {{nailDirective}}. {{lightingDirective}} Beauty-oriented framing with product as clear hero. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'portrait',
      },
      {
        id: 'makeup_flatlay', title: 'Cosmetic Flat Lay',
        description: 'Top-down arrangement in a clean or editorial layout.',
        promptTemplate: 'Top-down flat-lay beauty photograph — {{productName}} arranged in a curated cosmetic layout. {{surfaceDirective}} {{lightingDirective}} Sharp focus across all items — {{materialTexture}}, pigment colors, applicator details. Clean editorial arrangement with intentional spacing. {{stylingDirective}} {{accentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'flatlay',
      },
      {
        id: 'makeup_detail', title: 'Precision Detail Shot',
        description: 'Macro showing bullet shape, pigment surface, brush tip, or packaging finish.',
        promptTemplate: 'Extreme macro of {{productName}} — tack-sharp focus on {{focusArea}}: bullet shape, pigment surface texture, brush tip fibers, or packaging finish detail. {{materialTexture}} at maximum resolution. {{lightingDirective}} Shallow depth of field isolating the detail. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'macro',
      },
      {
        id: 'makeup_swatch_composition', title: 'Swatch & Product Scene',
        description: 'Product paired with pigment swatches, smears, or color payoff visuals.',
        promptTemplate: 'Swatch composition — {{productName}} paired with pigment swatches, color smears, or texture payoff on a clean surface. {{surfaceDirective}} Product in sharp focus alongside its color output — {{materialTexture}}. {{lightingDirective}} True-to-life color accuracy showing actual pigment depth and coverage. {{focusArea}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'macro',
      },
      {
        id: 'makeup_vanity_editorial', title: 'Vanity Beauty Scene',
        description: 'Makeup in a premium dressing-table or getting-ready environment.',
        promptTemplate: 'Vanity editorial scene — {{productName}} on a premium dressing table or beauty station. {{environmentDirective}} Mirror reflections, soft ambient lighting, getting-ready atmosphere. {{lightingDirective}} Product in sharp focus — {{materialTexture}}. {{moodDirective}} {{stylingDirective}} {{accentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment', 'visualDirection'], isGlobal: false, categoryCollection: 'makeup-lipsticks',
        sceneType: 'editorial',
      },
    ],
  },
  {
    id: 'bags-accessories',
    title: 'Bags & Structured Accessories',
    scenes: [
      {
        id: 'bag_hero_surface', title: 'Bag Hero on Surface',
        description: 'Bag on stone, wood, linen, or premium surface with clean composition.',
        promptTemplate: 'Luxury bag hero photograph — {{productName}} {{surfaceDirective}} with clean editorial composition. {{lightingDirective}} Tack-sharp focus on {{materialTexture}} — leather grain, stitching precision, edge paint, hardware finish. Structured silhouette clearly visible. {{shadowDirective}} {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'editorial',
      },
      {
        id: 'bag_pedestal_hero', title: 'Bag on Pedestal',
        description: 'Bag elevated on a block, pedestal, or sculptural display base.',
        promptTemplate: 'Premium display photograph — {{productName}} bag elevated on a sculptural pedestal or display block. {{lightingDirective}} Slightly low camera angle emphasizing bag stature and structure. {{materialTexture}} — leather grain, hardware gleam, stitching detail all razor-sharp. {{shadowDirective}} {{moodDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background', 'visualDirection'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'packshot',
      },
      {
        id: 'bag_carry_hold', title: 'Carry Shot',
        description: 'Bag being carried naturally in hand or at the side.',
        promptTemplate: 'Carry-shot photograph — {{productName}} bag being carried naturally at the side or in hand. {{personDirective}} {{outfitDirective}} Hyper-realistic skin on hands and arms — visible pores, natural anatomy, {{nailDirective}}. Bag showing {{materialTexture}} — leather, hardware, strap detail all sharp. {{lightingDirective}} {{actionDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'portrait',
      },
      {
        id: 'bag_portrait_editorial', title: 'Portrait with Bag',
        description: 'Model-centered shot where the bag is clearly visible and aspirational.',
        promptTemplate: 'Fashion portrait — model presenting {{productName}} bag in an aspirational editorial composition. {{personDirective}} {{outfitDirective}} Bag clearly visible as co-hero — {{materialTexture}}, hardware, silhouette all in sharp focus. {{lightingDirective}} {{moodDirective}} {{modelDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'portrait',
      },
      {
        id: 'bag_detail_macro', title: 'Hardware & Material Detail',
        description: 'Close-up of leather grain, stitching, clasp, zipper, or metal finish.',
        promptTemplate: 'Extreme close-up macro of {{productName}} bag construction. Tack-sharp focus on {{focusArea}} — visible micro-details: thread tension, pore structure of leather, brushed or polished metal finish, edge paint line, zipper teeth alignment. {{materialTexture}} at maximum resolution. Shallow depth of field. {{lightingDirective}} {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'macro',
      },
      {
        id: 'bag_seated_lifestyle', title: 'Seated Lifestyle with Bag',
        description: 'Bag in an interior scene beside or with a seated model.',
        promptTemplate: 'Lifestyle interior photograph — {{productName}} bag beside a seated model in a refined interior. {{personDirective}} {{outfitDirective}} {{environmentDirective}} Bag in sharp focus — {{materialTexture}}, hardware, and silhouette clear. Model and setting provide context with slight background blur. {{lightingDirective}} {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'sceneEnvironment'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'lifestyle',
      },
      {
        id: 'bag_furniture_placement', title: 'Bag on Furniture',
        description: 'Bag placed on a chair, bench, console, or side table.',
        promptTemplate: 'Interior styling photograph — {{productName}} bag placed on premium furniture (chair, bench, or console). {{surfaceDirective}} {{environmentDirective}} Bag in sharp focus — {{materialTexture}}, structured silhouette, hardware detail. Furniture provides textural contrast. {{lightingDirective}} {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'lifestyle',
      },
      {
        id: 'bag_walking_editorial', title: 'Walking Editorial',
        description: 'Bag styled in motion with walking composition.',
        promptTemplate: 'Fashion editorial motion shot — model walking with {{productName}} bag. {{personDirective}} {{outfitDirective}} Bag swinging naturally at side — {{materialTexture}}, strap tension, hardware gleam all visible. Slight motion blur on legs, bag remains sharp. {{lightingDirective}} {{actionDirective}} {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'bags-accessories',
        sceneType: 'editorial',
      },
    ],
  },
  {
    id: 'hats-small',
    title: 'Hats & Small Accessories',
    scenes: [
      {
        id: 'accessory_clean_hero', title: 'Clean Accessory Hero',
        description: 'Simple isolated accessory shot with minimal styling.',
        promptTemplate: 'Clean isolated product photograph of {{productName}} accessory on {{background}} background. {{lightingDirective}} Centered composition with sharp focus on {{materialTexture}} — every stitch, weave, clasp, or finish detail visible. {{shadowDirective}} True-to-life color accuracy. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background'], isGlobal: false, categoryCollection: 'hats-small',
        sceneType: 'packshot',
      },
      {
        id: 'accessory_styled_surface', title: 'Styled Surface Scene',
        description: 'Accessory on a styled surface with subtle props or textures.',
        promptTemplate: 'Styled surface photograph of {{productName}} accessory {{surfaceDirective}} with subtle contextual props. {{lightingDirective}} Sharp focus on product — {{materialTexture}}. Surface and props add texture and lifestyle context without competing. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'hats-small',
        sceneType: 'lifestyle',
      },
      {
        id: 'accessory_material_detail', title: 'Material Detail',
        description: 'Macro showing stitches, weave, edge finishing, leather, or metal.',
        promptTemplate: 'Extreme macro of {{productName}} accessory materials — tack-sharp focus on {{focusArea}}: stitching, weave pattern, edge finishing, metal hardware, or leather grain. {{materialTexture}} at maximum resolution. {{lightingDirective}} Shallow depth of field. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'hats-small',
        sceneType: 'macro',
      },
      {
        id: 'accessory_hold_context', title: 'Held in Context',
        description: 'Accessory held in hand or partially styled in a real-life scene.',
        promptTemplate: 'Contextual photograph — {{productName}} accessory held in a {{handStyle}} hand or partially styled. {{personDirective}} Natural skin texture with visible pores, {{nailDirective}}. Product showing {{materialTexture}} in sharp focus. {{lightingDirective}} {{environmentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'hats-small',
        sceneType: 'portrait',
      },
      {
        id: 'accessory_fashion_editorial', title: 'Fashion Editorial',
        description: 'Accessory integrated into a fashion composition.',
        promptTemplate: 'Fashion editorial composition featuring {{productName}} accessory as the styling hero. {{lightingDirective}} {{moodDirective}} Dramatic composition with intentional framing. Product in sharp focus — {{materialTexture}}. {{stylingDirective}} {{accentDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'hats-small',
        sceneType: 'editorial',
      },
      {
        id: 'accessory_on_body_crop', title: 'On-Body Crop',
        description: 'Accessory worn or shown on body in a tight crop.',
        promptTemplate: 'Tight on-body crop — {{productName}} accessory worn or styled on the body. {{personDirective}} {{outfitDirective}} Hyper-realistic skin texture where visible. Product showing {{materialTexture}} in tack-sharp focus. {{lightingDirective}} {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'hats-small',
        sceneType: 'portrait',
      },
    ],
  },
  {
    id: 'shoes',
    title: 'Shoes',
    scenes: [
      {
        id: 'shoes_side_profile_hero', title: 'Side Profile Hero',
        description: 'Strong side profile emphasizing silhouette and structure.',
        promptTemplate: 'Side profile hero photograph of {{productName}} shoe. Strong silhouette shot emphasizing structure, sole thickness, and design lines. {{lightingDirective}} {{shadowDirective}} Tack-sharp focus on {{materialTexture}} — leather, suede, or fabric texture, stitching, sole edges. Clean {{background}} background. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'packshot',
      },
      {
        id: 'shoes_pair_display', title: 'Pair Composition',
        description: 'Both shoes arranged together in a balanced composition.',
        promptTemplate: 'Pair composition photograph — both {{productName}} shoes arranged in a balanced, slightly angled display. {{lightingDirective}} {{shadowDirective}} Sharp focus on both shoes — {{materialTexture}}, lace detail, sole construction. Clean {{background}} background with consistent lighting. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'packshot',
      },
      {
        id: 'shoes_sole_detail', title: 'Sole Detail',
        description: 'Bottom view or angled close-up of outsole and tread.',
        promptTemplate: 'Outsole detail photograph of {{productName}} — bottom view or dramatic angle showing tread pattern, sole construction, brand markings. Tack-sharp focus on {{focusArea}} — rubber texture, grip pattern, stitching where sole meets upper. {{lightingDirective}} {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'macro',
      },
      {
        id: 'shoes_material_lace_detail', title: 'Material & Lace Detail',
        description: 'Close-up of leather, suede, stitching, lace structure.',
        promptTemplate: 'Material macro of {{productName}} shoe — extreme close-up on {{focusArea}}: leather grain, suede nap, stitching thread, lace eyelet, or tongue label. {{materialTexture}} at maximum resolution. {{lightingDirective}} Shallow depth of field with precise focal plane. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'macro',
      },
      {
        id: 'shoes_lifestyle_scene', title: 'Lifestyle Footwear Scene',
        description: 'Shoes in a real environment, worn or placed naturally.',
        promptTemplate: 'Lifestyle footwear photograph — {{productName}} shoes in a real environment, either worn or placed naturally. {{environmentDirective}} {{lightingDirective}} Sharp focus on shoes — {{materialTexture}} clearly visible. Environment provides context with gentle background blur. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'lifestyle',
      },
      {
        id: 'shoes_on_foot_editorial', title: 'On-Foot Editorial',
        description: 'Cropped editorial shot worn by a model.',
        promptTemplate: 'On-foot editorial — {{productName}} shoes worn by a model in a cropped fashion composition. {{personDirective}} {{outfitDirective}} Hyper-realistic skin texture on ankles and feet where visible. Shoes in tack-sharp focus — {{materialTexture}}, sole, lacing all detailed. {{lightingDirective}} {{actionDirective}} {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'portrait',
      },
      {
        id: 'shoes_pedestal_hero', title: 'Pedestal Shoe Hero',
        description: 'Single shoe elevated on a block or display base.',
        promptTemplate: 'Premium display — single {{productName}} shoe elevated on a sculptural pedestal or display block. Slightly low camera angle emphasizing structure and silhouette. {{lightingDirective}} {{shadowDirective}} Tack-sharp focus on {{materialTexture}}. {{moodDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background', 'visualDirection'], isGlobal: false, categoryCollection: 'shoes',
        sceneType: 'packshot',
      },
    ],
  },
  {
    id: 'garments',
    title: 'Clothing & Apparel',
    scenes: [
      {
        id: 'apparel_folded_display', title: 'Folded Display',
        description: 'Garment folded neatly for surface-based product storytelling.',
        promptTemplate: 'Folded garment photograph — {{productName}} neatly folded on a {{background}} surface. {{lightingDirective}} Sharp focus on fabric fold structure — {{materialTexture}}, weave, color depth. Clean, minimal composition emphasizing fabric quality and color accuracy. {{shadowDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'packshot',
      },
      {
        id: 'apparel_hanging_display', title: 'Hanging Display',
        description: 'Garment on hanger, rack, or hook in a clean fashion setting.',
        promptTemplate: 'Hanging garment photograph — {{productName}} on a quality hanger or rack in a clean fashion setting. {{lightingDirective}} Full garment visible — {{materialTexture}}, drape, silhouette, seam construction. {{background}} background. Natural gravity drape showing fabric weight and fall. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'packshot',
      },
      {
        id: 'apparel_styled_flatlay', title: 'Styled Flat Lay',
        description: 'Top-down arrangement with optional accessories.',
        promptTemplate: 'Top-down flat-lay — {{productName}} garment arranged with curated accessories on a styled surface. {{surfaceDirective}} {{lightingDirective}} Sharp focus on fabric — {{materialTexture}}, color depth, print detail. Clean editorial arrangement with intentional spacing. {{stylingDirective}} {{accentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'flatlay',
      },
      {
        id: 'apparel_fabric_stitch_detail', title: 'Fabric & Stitch Detail',
        description: 'Macro showing material texture, seams, buttons, or label.',
        promptTemplate: 'Fabric macro of {{productName}} — extreme close-up on {{focusArea}}: weave structure, thread count, seam construction, button attachment, label printing. {{materialTexture}} at maximum resolution. {{lightingDirective}} Shallow depth of field. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'macro',
      },
      {
        id: 'apparel_editorial_garment', title: 'Editorial Garment Shot',
        description: 'Garment in a styled premium fashion composition.',
        promptTemplate: 'Editorial fashion composition — {{productName}} garment styled in a premium fashion setting. {{lightingDirective}} {{moodDirective}} Fabric in sharp focus — {{materialTexture}}, color saturation, drape quality. {{stylingDirective}} {{accentDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'editorial',
      },
      {
        id: 'apparel_on_model_editorial', title: 'On-Model Look',
        description: 'Full or half-body model shot focused on fit and silhouette.',
        promptTemplate: 'On-model fashion photograph — {{productName}} worn by model showing fit, silhouette, and drape. {{bodyFramingDirective}} {{personDirective}} {{outfitDirective}} Hyper-realistic skin texture where visible. Fabric showing {{materialTexture}} — weave, color depth, construction quality. {{lightingDirective}} {{moodDirective}} {{modelDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'portrait',
      },
      {
        id: 'apparel_motion_scene', title: 'Movement Shot',
        description: 'Garment shown in motion for drape, softness, or fluidity.',
        promptTemplate: 'Motion fashion photograph — {{productName}} garment in movement showing fabric fluidity, drape, and flow. {{bodyFramingDirective}} {{personDirective}} {{outfitDirective}} Fabric captured mid-motion — {{materialTexture}}, showing weight and movement quality. Slight motion blur on extremities, garment detail remains sharp. {{lightingDirective}} {{actionDirective}} {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'garments',
        sceneType: 'editorial',
      },
    ],
  },
  {
    id: 'home-decor',
    title: 'Home Decor / Furniture',
    scenes: [
      {
        id: 'home_interior_placement', title: 'Interior Placement',
        description: 'Product placed naturally inside a styled interior space.',
        promptTemplate: 'Interior styling photograph — {{productName}} placed naturally in a styled room. {{environmentDirective}} {{lightingDirective}} Product in sharp focus — {{materialTexture}}, finish quality, construction detail. Room provides context with natural depth blur. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment', 'productSize'], isGlobal: false, categoryCollection: 'home-decor',
        sceneType: 'lifestyle',
      },
      {
        id: 'home_surface_styling', title: 'Shelf or Surface Styling',
        description: 'Object on shelf, coffee table, sideboard, or nightstand.',
        promptTemplate: 'Surface styling photograph — {{productName}} on a shelf, coffee table, or sideboard. {{surfaceDirective}} {{lightingDirective}} Product in sharp focus — {{materialTexture}}, craftsmanship detail. Surrounding objects provide scale and lifestyle context. {{environmentDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'home-decor',
        sceneType: 'lifestyle',
      },
      {
        id: 'home_material_detail', title: 'Material Detail',
        description: 'Macro showing finish, grain, texture, fabric, or craftsmanship.',
        promptTemplate: 'Material macro of {{productName}} — extreme close-up on {{focusArea}}: wood grain, ceramic glaze, fabric weave, metal patina, or craftsmanship joints. {{materialTexture}} at maximum resolution. {{lightingDirective}} Shallow depth of field. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'home-decor',
        sceneType: 'macro',
      },
      {
        id: 'home_wide_room_crop', title: 'Wide Room Crop',
        description: 'Wider shot showing product in room context.',
        promptTemplate: 'Wide room context photograph — {{productName}} in a furnished interior showing its scale and placement. {{environmentDirective}} {{lightingDirective}} Product identifiable and in focus within the wider scene. Natural interior lighting with depth. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment', 'productSize'], isGlobal: false, categoryCollection: 'home-decor',
        sceneType: 'lifestyle',
      },
      {
        id: 'home_editorial_scene', title: 'Decor Editorial Scene',
        description: 'Campaign-style styled image with premium atmosphere.',
        promptTemplate: 'Editorial home decor composition — {{productName}} in a campaign-style premium interior setting. {{lightingDirective}} {{moodDirective}} Product as hero — {{materialTexture}}, finish, and form sharply rendered. Dramatic composition with intentional styling. {{stylingDirective}} {{accentDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'home-decor',
        sceneType: 'editorial',
      },
      {
        id: 'home_cluster_composition', title: 'Object Cluster Composition',
        description: 'Decor grouped with complementary objects in a styling setup.',
        promptTemplate: 'Cluster composition — {{productName}} grouped with complementary decor objects in a curated styling arrangement. {{surfaceDirective}} {{lightingDirective}} Hero product in sharpest focus — {{materialTexture}}. Supporting objects provide scale and aesthetic context. {{stylingDirective}} {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'home-decor',
        sceneType: 'lifestyle',
      },
    ],
  },
  {
    id: 'tech-devices',
    title: 'Tech / Devices',
    scenes: [
      {
        id: 'tech_clean_packshot', title: 'Clean Device Packshot',
        description: 'Minimal device-only shot with controlled reflections.',
        promptTemplate: 'Clean device packshot of {{productName}} on {{background}} background. {{lightingDirective}} Controlled reflections on screen and body surfaces. Tack-sharp focus on {{materialTexture}} — aluminum, glass, plastic finish, port details, button edges. {{shadowDirective}} Precise color accuracy. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['background'], isGlobal: false, categoryCollection: 'tech-devices',
        sceneType: 'packshot',
      },
      {
        id: 'tech_desk_placement', title: 'Desk Placement',
        description: 'Device on a desk, workstation, or creative setup.',
        promptTemplate: 'Desk placement photograph — {{productName}} on a styled desk or workstation. {{environmentDirective}} {{surfaceDirective}} {{lightingDirective}} Device in sharp focus — {{materialTexture}}, screen clarity, port and button detail. Desk accessories provide professional context. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'tech-devices',
        sceneType: 'lifestyle',
      },
      {
        id: 'tech_use_interaction', title: 'Use Interaction Shot',
        description: 'Hand or person interacting with the device.',
        promptTemplate: 'Interaction photograph — {{handStyle}} hand using {{productName}} device. {{personDirective}} Hyper-realistic skin texture with visible pores and fingerprints on screen. Device showing {{materialTexture}} — screen, buttons, ports all in sharp focus. {{lightingDirective}} {{actionDirective}} {{environmentDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'tech-devices',
        sceneType: 'portrait',
      },
      {
        id: 'tech_interface_detail', title: 'Interface / Component Detail',
        description: 'Tight close-up of ports, buttons, lens, or UI.',
        promptTemplate: 'Component macro of {{productName}} — extreme close-up on {{focusArea}}: port openings, button mechanism, lens assembly, or physical UI elements. {{materialTexture}} at maximum resolution — machining precision, material joints, finish quality. {{lightingDirective}} Shallow depth of field. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'tech-devices',
        sceneType: 'macro',
      },
      {
        id: 'tech_editorial_scene', title: 'Tech Editorial Scene',
        description: 'High-end campaign composition with futuristic polish.',
        promptTemplate: 'Tech editorial composition — {{productName}} in a high-end campaign setting with futuristic polish. {{lightingDirective}} {{moodDirective}} Clean specular highlights on surfaces — {{materialTexture}}. Dramatic composition with precise negative space. {{stylingDirective}} {{accentDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'tech-devices',
        sceneType: 'editorial',
      },
      {
        id: 'tech_environment_context', title: 'Device in Environment',
        description: 'Product in the place it belongs: office, home, or studio.',
        promptTemplate: 'Contextual environment photograph — {{productName}} in its natural use environment (office, home studio, or creative space). {{environmentDirective}} {{lightingDirective}} Device in sharp focus — {{materialTexture}}. Environment suggests daily use with natural depth blur. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'tech-devices',
        sceneType: 'lifestyle',
      },
    ],
  },
  {
    id: 'food-beverage',
    title: 'Food & Beverage',
    scenes: [
      {
        id: 'food_tabletop_placement', title: 'Tabletop Product Placement',
        description: 'Product styled on a table, counter, or serving surface.',
        promptTemplate: 'Food product photograph — {{productName}} styled on a tabletop or serving surface. {{surfaceDirective}} {{lightingDirective}} Product packaging and label in sharp focus — {{materialTexture}}. Warm, appetite-enhancing color temperature. {{environmentDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'lifestyle',
      },
      {
        id: 'food_ingredient_flatlay', title: 'Ingredient Flat Lay',
        description: 'Top-down composition with ingredients or garnishes.',
        promptTemplate: 'Top-down ingredient flat-lay — {{productName}} arranged with fresh ingredients, garnishes, or recipe components. {{surfaceDirective}} {{lightingDirective}} Product as hero with surrounding ingredients providing flavor context. Sharp focus on {{materialTexture}} and ingredient textures — visible freshness and natural imperfections. {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'flatlay',
      },
      {
        id: 'food_packaging_detail', title: 'Packaging Detail',
        description: 'Close-up of label, material, seal, or printed finish.',
        promptTemplate: 'Packaging macro of {{productName}} — close-up on {{focusArea}}: label printing, seal integrity, material texture, nutritional panel. {{materialTexture}} at high resolution — printed text legibility, foil or matte finish. {{lightingDirective}} {{packagingDirective}} {{cropDirective}} {{brandingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus', 'packagingDetails'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'macro',
      },
      {
        id: 'food_in_hand', title: 'In-Hand Food or Drink',
        description: 'Product shown being held or served for scale.',
        promptTemplate: 'Hand-held food product photograph — {{productName}} held naturally in a {{handStyle}} hand. {{personDirective}} Hyper-realistic skin texture — visible pores, natural grip. Product showing {{materialTexture}} and label in sharp focus. {{lightingDirective}} Warm, inviting color temperature. {{actionDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'portrait',
      },
      {
        id: 'food_product_packaging', title: 'Product & Packaging Scene',
        description: 'Food/beverage with its container, box, or bottle.',
        promptTemplate: 'Product and packaging composition — {{productName}} with its container, box, or outer packaging. {{packagingDirective}} Both in sharp focus — {{materialTexture}} on product, packaging construction and print quality visible. {{lightingDirective}} {{brandingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['packagingDetails'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'packshot',
      },
      {
        id: 'food_pour_serve_action', title: 'Pour / Serve Action',
        description: 'Visual of pouring, scooping, or opening the product.',
        promptTemplate: 'Action photograph — {{productName}} being poured, scooped, or served. {{personDirective}} {{handStyle}} hand performing the action with natural skin texture. Liquid flow, powder scatter, or food texture captured mid-action. {{lightingDirective}} {{actionDirective}} Sharp focus on the action moment. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails', 'actionDetails'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'portrait',
      },
      {
        id: 'food_lifestyle_context', title: 'Consumption Context',
        description: 'Product in a believable eating or drinking environment.',
        promptTemplate: 'Lifestyle consumption photograph — {{productName}} in a natural eating or drinking environment. {{environmentDirective}} {{lightingDirective}} Product identifiable with {{materialTexture}} and label visible. Warm, inviting atmosphere suggesting real daily use. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'food-beverage',
        sceneType: 'lifestyle',
      },
    ],
  },
  {
    id: 'supplements-wellness',
    title: 'Supplements & Wellness',
    scenes: [
      {
        id: 'wellness_shelf_placement', title: 'Wellness Shelf Placement',
        description: 'Product on shelf or cabinet in a wellness-oriented environment.',
        promptTemplate: 'Wellness interior photograph — {{productName}} on a shelf or cabinet in a clean, health-oriented environment. {{environmentDirective}} {{lightingDirective}} Product in sharp focus — {{materialTexture}}, label legibility, cap or dispenser detail. Natural, calming atmosphere. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'lifestyle',
      },
      {
        id: 'wellness_tabletop', title: 'Tabletop Product Shot',
        description: 'Bottle, pouch, or jar styled on a clean tabletop.',
        promptTemplate: 'Tabletop wellness photograph — {{productName}} (bottle, pouch, or jar) styled on a clean surface. {{surfaceDirective}} {{lightingDirective}} Sharp focus on {{materialTexture}} — label detail, cap construction, container finish. Clean, healthy aesthetic. {{moodDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'lifestyle',
      },
      {
        id: 'wellness_label_detail', title: 'Label & Packaging Detail',
        description: 'Macro emphasizing ingredients panel, label clarity, or packaging.',
        promptTemplate: 'Label macro of {{productName}} — extreme close-up on {{focusArea}}: ingredients panel, nutritional facts, label printing quality, packaging seal. {{materialTexture}} of container visible. Printed text legible at full resolution. {{lightingDirective}} {{cropDirective}} {{brandingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'macro',
      },
      {
        id: 'wellness_in_hand', title: 'In-Hand Supplement Shot',
        description: 'Bottle or sachet held naturally in a health composition.',
        promptTemplate: 'Hand-held wellness photograph — {{productName}} held naturally in a {{handStyle}} hand. {{personDirective}} Healthy, natural skin texture with visible pores. Product showing {{materialTexture}} and label in sharp focus. {{lightingDirective}} Clean, health-oriented composition. {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'portrait',
      },
      {
        id: 'wellness_product_packaging', title: 'Product & Packaging Composition',
        description: 'Primary product with carton, refill, or sachets.',
        promptTemplate: 'Packaging composition — {{productName}} with its outer carton, refill sachets, or secondary packaging. {{packagingDirective}} Both in sharp focus — {{materialTexture}} on product, packaging print quality and construction visible. {{lightingDirective}} {{brandingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['packagingDetails'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'packshot',
      },
      {
        id: 'wellness_daily_routine', title: 'Daily Routine Scene',
        description: 'Product in a realistic morning or wellness ritual context.',
        promptTemplate: 'Daily routine photograph — {{productName}} in a realistic morning wellness ritual setting. {{environmentDirective}} Alongside natural props (water glass, fruit, yoga mat). {{lightingDirective}} Product in sharp focus — {{materialTexture}}. Warm, healthy morning atmosphere. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'lifestyle',
      },
      {
        id: 'wellness_dose_detail', title: 'Dose / Scoop Detail',
        description: 'Close-up of scoop, capsule, powder, tablet, or serving format.',
        promptTemplate: 'Dose detail photograph — extreme close-up of {{productName}} serving format: scoop of powder, capsule, tablet, or sachet contents. Tack-sharp focus on {{focusArea}} — granule texture, capsule seam, powder consistency. {{lightingDirective}} Shallow depth of field. Product container visible in soft background blur. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'supplements-wellness',
        sceneType: 'macro',
      },
    ],
  },
  {
    id: 'other',
    title: 'Other / Custom',
    scenes: [
      {
        id: 'global_hero_surface', title: 'Hero on Surface',
        description: 'Product hero shot on a styled surface.',
        promptTemplate: 'Hero product photograph — {{productName}} {{surfaceDirective}} in a clean editorial composition. {{lightingDirective}} Tack-sharp focus on {{materialTexture}}. {{shadowDirective}} {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'other',
        sceneType: 'editorial',
      },
      {
        id: 'global_in_hand', title: 'Product in Hand',
        description: 'Product held for scale and context.',
        promptTemplate: 'Hand-held product photograph — {{productName}} held in a {{handStyle}} hand for scale and context. {{personDirective}} Hyper-realistic skin texture with visible pores, {{nailDirective}}. Product showing {{materialTexture}} in sharp focus. {{lightingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['personDetails'], isGlobal: false, categoryCollection: 'other',
        sceneType: 'portrait',
      },
      {
        id: 'global_detail_macro', title: 'Detail Close-Up',
        description: 'Macro or detail shot of key product features.',
        promptTemplate: 'Macro detail photograph of {{productName}} — tack-sharp focus on {{focusArea}}: {{materialTexture}} at maximum resolution. Visible micro-details proving quality and craftsmanship. {{lightingDirective}} Shallow depth of field. {{cropDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['detailFocus'], isGlobal: false, categoryCollection: 'other',
        sceneType: 'macro',
      },
      {
        id: 'global_shelf_placement', title: 'Shelf Placement',
        description: 'Product on a shelf or display surface.',
        promptTemplate: 'Shelf placement photograph — {{productName}} on a styled shelf or display surface. {{environmentDirective}} {{lightingDirective}} Product in sharp focus — {{materialTexture}}. Surrounding context provides natural lifestyle framing. {{moodDirective}} {{stylingDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['sceneEnvironment'], isGlobal: false, categoryCollection: 'other',
        sceneType: 'lifestyle',
      },
      {
        id: 'global_editorial_scene', title: 'Editorial Composition',
        description: 'Campaign-style editorial shot.',
        promptTemplate: 'Editorial campaign photograph — {{productName}} in a styled premium composition. {{lightingDirective}} {{moodDirective}} Product as hero — {{materialTexture}} rendered with precision. Dramatic composition with intentional framing. {{stylingDirective}} {{accentDirective}} {{productProminenceDirective}} {{consistencyDirective}} {{cameraDirective}}',
        triggerBlocks: ['visualDirection'], isGlobal: false, categoryCollection: 'other',
        sceneType: 'editorial',
      },
    ],
  },
];

export const ALL_SCENES: ProductImageScene[] = [
  ...GLOBAL_SCENES,
  ...CATEGORY_COLLECTIONS.flatMap(c => c.scenes),
];

export function getSceneById(id: string): ProductImageScene | undefined {
  return ALL_SCENES.find(s => s.id === id);
}

/** Get category collection ID that a scene belongs to */
export function getSceneCategoryId(sceneId: string): string | null {
  for (const col of CATEGORY_COLLECTIONS) {
    if (col.scenes.some(s => s.id === sceneId)) return col.id;
  }
  return null;
}
