import { PageLayout } from '@/components/landing/PageLayout';
import { FileText } from 'lucide-react';

export default function TermsOfService() {
  return (
    <PageLayout>
      <section className="py-20 sm:py-28">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium mb-6">
              <FileText className="w-4 h-4" />
              Legal
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold text-foreground tracking-tight mb-4">
              Terms of Service
            </h1>
            <p className="text-sm text-muted-foreground">Last updated: February 2026</p>
          </div>

          <div className="prose prose-sm max-w-none text-muted-foreground [&_h2]:text-foreground [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:mt-10 [&_h2]:mb-4 [&_h3]:text-foreground [&_h3]:font-medium [&_h3]:mt-6 [&_h3]:mb-2 [&_p]:mb-4 [&_p]:leading-relaxed [&_ul]:mb-4 [&_ul]:space-y-1 [&_li]:ml-4">
            <p>
              <em>
                This is a template terms of service provided for informational purposes. We recommend consulting with a legal professional to ensure compliance with applicable laws.
              </em>
            </p>

            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using VOVV.AI (the "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service. These Terms constitute a legally binding agreement between you and VOVV.AI.
            </p>

            <h2>2. Account Registration</h2>
            <p>
              You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information and keep it updated.
            </p>

            <h2>3. Service Description</h2>
            <p>
              VOVV.AI provides AI-powered product photography generation tools. You upload product images, and our Service generates styled product photographs, lifestyle images, on-model shots, and videos based on your selections and inputs.
            </p>

            <h2>4. Credits and Payment</h2>
            <p>
              The Service operates on a credit-based system. Credits are consumed when generating images or videos. Credit allocations depend on your subscription plan. Purchased credits are non-refundable except as described in our refund policy. We reserve the right to modify pricing with 30 days' notice.
            </p>

            <h2>5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>• Use the Service to generate illegal, harmful, or misleading content</li>
              <li>• Upload content you do not have the right to use</li>
              <li>• Attempt to reverse-engineer, copy, or extract our AI models</li>
              <li>• Use automated scripts to access the Service without permission</li>
              <li>• Resell or redistribute the Service without authorization</li>
              <li>• Interfere with or disrupt the Service or its infrastructure</li>
            </ul>

            <h2>6. Intellectual Property</h2>
            <h3>Your Content</h3>
            <p>
              You retain all rights to the product images you upload and the content generated by the Service. By uploading images, you grant us a limited license to process them solely for providing the Service.
            </p>
            <h3>Our Property</h3>
            <p>
              The Service, including its design, features, AI models, and branding, is owned by VOVV.AI and protected by intellectual property laws. Nothing in these Terms grants you rights to our trademarks, logos, or proprietary technology.
            </p>

            <h2>7. AI-Generated Content</h2>
            <p>
              Content generated by the Service is created by artificial intelligence and may not be perfect. While we strive for high quality, we do not guarantee that generated images will be free from artifacts, inaccuracies, or imperfections. You are responsible for reviewing generated content before using it commercially.
            </p>

            <h2>8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, VOVV.AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the Service. Our total liability shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>

            <h2>9. Disclaimer of Warranties</h2>
            <p>
              The Service is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Service will be uninterrupted, error-free, or secure.
            </p>

            <h2>10. Termination</h2>
            <p>
              You may terminate your account at any time through the Settings page. We may suspend or terminate your access if you violate these Terms or engage in conduct that we determine is harmful to the Service or other users. Upon termination, your right to use the Service ceases immediately.
            </p>

            <h2>11. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. We will notify you of material changes via email or through the Service at least 30 days before they take effect. Continued use after changes constitutes acceptance.
            </p>

            <h2>12. Governing Law</h2>
            <p>
              These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles.
            </p>

            <h2>13. Contact Us</h2>
            <p>
              Questions about these Terms? Contact us at{' '}
              <a href="mailto:legal@vovv.ai" className="text-primary hover:underline">
                legal@vovv.ai
              </a>
              .
            </p>
          </div>
        </div>
      </section>
    </PageLayout>
  );
}
