
UPDATE product_image_scenes SET
  sub_category = 'Living Room',
  prompt_template = E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nIMPORTANT — DIMENSIONAL ACCURACY: If {{productName}} has known dimensions (e.g. 220cm sofa, 120cm coffee table, 180cm TV unit), use those measurements to place the product at correct real-world scale relative to the room architecture. Standard room reference: ceiling height ~2.7m, standard door ~2.1m tall × 0.9m wide, floor tiles ~60cm. The product must never appear miniaturized or oversized — match proportions precisely against surrounding architectural elements.\n\nCreate a premium lifestyle interior image placing {{productName}} in an expansive open-plan penthouse living space on a high floor with floor-to-ceiling panoramic windows (3.5m+ height) revealing a twilight city skyline. Polished concrete floors with subtle warm reflections. Brass and brushed gold accent fixtures — floor lamps, side tables. Muted earth-tone palette: warm taupe walls, charcoal architectural columns, soft cream textiles.\n\nThe furniture must remain the clear visual hero, correctly scaled and grounded in the space. Room dimensions feel approximately 8m × 6m with 3.5m ceiling height.\n\nLighting: golden hour warmth flooding through windows, supplemented by warm accent lamps creating pools of light. Soft ambient glow, no harsh shadows.\n\nShot with 28mm lens, eye-level perspective, wide composition. Shallow depth of field on background cityscape. Editorial luxury interiors — Architectural Digest aesthetic. No clutter, no text.'
WHERE scene_id = 'furniture-lifestyle-penthouse-panorama';

UPDATE product_image_scenes SET
  sub_category = 'Living Room',
  prompt_template = E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nIMPORTANT — DIMENSIONAL ACCURACY: If {{productName}} has known dimensions (e.g. 220cm sofa, 120cm coffee table, 180cm TV unit), use those measurements to place the product at correct real-world scale relative to the room architecture. Standard room reference: ceiling height ~2.7m, standard door ~2.1m tall × 0.9m wide, floor tiles ~60cm. The product must never appear miniaturized or oversized — match proportions precisely against surrounding architectural elements.\n\nCreate a premium lifestyle interior image placing {{productName}} in a bright, airy Mediterranean-inspired salon with tall arched doorways (2.4m height) and smooth off-white lime-washed plaster walls. Wide-plank herringbone European oak flooring in a warm honey tone. Subtle plaster crown molding. A tall arched window with sheer linen curtains billowing gently, a recessed niche with a single ceramic vase. A woven jute rug partially visible. A small olive tree in a terracotta pot in the far corner.\n\nThe furniture must remain visually dominant, correctly scaled and grounded. Room feels approximately 6m × 5m with 3m ceiling height. Color palette: ivory, warm sand, soft terracotta accents, natural linen tones.\n\nLighting: soft diffused morning sunlight streaming through arched windows, creating gentle warm shadows on the floor.\n\nShot with 35mm lens, slightly elevated angle (10-15 degrees), centered composition. Quiet luxury Mediterranean editorial — Elle Décor aesthetic. No clutter, no text.'
WHERE scene_id = 'furniture-lifestyle-ivory-boucle-salon';

UPDATE product_image_scenes SET
  sub_category = 'Living Room',
  prompt_template = E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nIMPORTANT — DIMENSIONAL ACCURACY: If {{productName}} has known dimensions (e.g. 220cm sofa, 120cm coffee table, 180cm TV unit), use those measurements to place the product at correct real-world scale relative to the room architecture. Standard room reference: ceiling height ~2.7m, standard door ~2.1m tall × 0.9m wide, floor tiles ~60cm. The product must never appear miniaturized or oversized — match proportions precisely against surrounding architectural elements.\n\nCreate a premium lifestyle interior image placing {{productName}} in an intimate yet spacious mid-century modern living room (approximately 5.5m × 4.5m, 2.8m ceiling) with rich walnut wood wall paneling and travertine stone flooring with subtle veining. A built-in walnut credenza (180cm wide) with curated art books and a bronze sculpture. A round travertine pedestal side table (50cm diameter) nearby. A large framed black-and-white photograph (100cm × 80cm) on the paneled wall. A sputnik-style brass chandelier providing warm downlight.\n\nThe furniture must remain the clear visual hero. Color palette: deep walnut brown, cream travertine, burnished brass, warm cognac leather tones, muted olive green accents.\n\nLighting: warm layered interior — overhead chandelier ambient glow, brass arc floor lamp creating a reading pool of light, subtle uplighting on the paneled wall.\n\nShot with 35mm lens, eye-level, slightly off-center composition creating depth. Mid-century collector aesthetic. No clutter, no text.'
WHERE scene_id = 'furniture-lifestyle-walnut-travertine-den';

UPDATE product_image_scenes SET
  sub_category = 'Living Room',
  prompt_template = E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nIMPORTANT — DIMENSIONAL ACCURACY: If {{productName}} has known dimensions (e.g. 220cm sofa, 120cm coffee table, 180cm TV unit), use those measurements to place the product at correct real-world scale relative to the room architecture. Standard room reference: ceiling height ~2.7m, standard door ~2.1m tall × 0.9m wide, floor tiles ~60cm. The product must never appear miniaturized or oversized — match proportions precisely against surrounding architectural elements.\n\nCreate a premium lifestyle interior image placing {{productName}} in a dramatic open-plan loft (approximately 10m × 7m, 4.5m ceiling) with soaring ceilings, exposed blackened steel I-beams, and dark honed slate tile flooring. Raw charcoal-toned concrete walls with subtle texture. Large steel-framed factory windows (3m+ tall) along one wall. A tall steel bookshelf (220cm) with dark-spined books and matte black objects against the far wall. A single oversized concrete planter (90cm tall) with a fiddle-leaf fig tree. Exposed ductwork and pendant cage lights on the ceiling.\n\nThe furniture must remain visually dominant and correctly scaled. Color palette: charcoal, graphite, matte black, warm concrete gray, dark bronze. One accent: a single deep burgundy throw or cushion.\n\nLighting: dramatic directional — strong sidelight from industrial windows creating deep shadows and contrast. Warm pendant lights adding focused pools of amber.\n\nShot with 24mm lens, low angle (floor-level perspective), wide composition emphasizing vertical scale. Dark luxury industrial editorial — Cereal Magazine aesthetic. No clutter, no text.'
WHERE scene_id = 'furniture-lifestyle-smoke-stone-loft';

UPDATE product_image_scenes SET
  sub_category = 'Living Room',
  prompt_template = E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nIMPORTANT — DIMENSIONAL ACCURACY: If {{productName}} has known dimensions (e.g. 220cm sofa, 120cm coffee table, 180cm TV unit), use those measurements to place the product at correct real-world scale relative to the room architecture. Standard room reference: ceiling height ~2.7m, standard door ~2.1m tall × 0.9m wide, floor tiles ~60cm. The product must never appear miniaturized or oversized — match proportions precisely against surrounding architectural elements.\n\nCreate a premium lifestyle interior image placing {{productName}} in a serene Scandinavian minimalist living space (approximately 6m × 5m, 2.7m ceiling) with wide-plank light ash wood flooring and walls painted in pale sage green (muted, almost gray-green). Large oversized windows (2.2m tall × 1.8m wide) framing a view of dense birch and pine forest outside. A low-profile white oak media unit (160cm wide) beneath the main window, a single sheepskin draped over a minimal wooden stool, a stack of design books on the floor. A woven wool rug in oatmeal/cream partially visible. One tall ceramic floor vase (70cm) with dried pampas grass in the corner.\n\nThe furniture must remain the clear visual hero. Color palette: pale sage, warm white, natural ash, oatmeal, soft moss green. No bright colors — everything muted and tonal.\n\nLighting: clean, even Nordic daylight streaming through large windows. Soft shadows, no harsh contrast. Cool-neutral with slight warmth from wood tones.\n\nShot with 35mm lens, eye-level, centered symmetrical composition. Scandinavian interiors editorial — Kinfolk aesthetic. No clutter, no text.'
WHERE scene_id = 'furniture-lifestyle-nordic-fjord';

UPDATE product_image_scenes SET
  sub_category = 'Living Room',
  prompt_template = E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nIMPORTANT — DIMENSIONAL ACCURACY: If {{productName}} has known dimensions (e.g. 220cm sofa, 120cm coffee table, 180cm TV unit), use those measurements to place the product at correct real-world scale relative to the room architecture. Standard room reference: ceiling height ~2.7m, standard door ~2.1m tall × 0.9m wide, floor tiles ~60cm. The product must never appear miniaturized or oversized — match proportions precisely against surrounding architectural elements.\n\nCreate a premium lifestyle interior image placing {{productName}} in a majestic high-ceiling Parisian room (approximately 7m × 6m, 4m+ ceiling) with classic Haussmann-style ornate plaster crown moldings and ceiling rosette. Dark espresso herringbone parquet flooring with a rich patina. Walls in a deep warm off-white (slightly aged, like old Parisian plaster). Tall French doors (2.8m height) with wrought-iron balcony railings visible. An ornate gilded mirror (2m tall, floor-standing, slightly aged) leaning against the far wall. A crystal chandelier overhead casting prismatic light patterns. A marble fireplace mantel (130cm wide) with a clock and candlesticks. Sheer voile curtains filtering afternoon light.\n\nThe furniture must remain visually dominant and correctly scaled. Color palette: warm ivory walls, dark espresso wood, aged gold, crystal, charcoal accents.\n\nLighting: warm afternoon Parisian light filtering through French doors, creating long golden shadows across the parquet. Chandelier adds sparkle and ambient warmth.\n\nShot with 28mm lens, slightly wide, eye-level perspective capturing ceiling height and floor expanse. Parisian haute couture interiors editorial — Vogue Living aesthetic. No clutter, no text.'
WHERE scene_id = 'furniture-lifestyle-grand-atelier-salon';
