-- 1. Add COMPLETE INTERIOR COMPOSITION to existing 12 bedroom scenes
UPDATE product_image_scenes
SET prompt_template = regexp_replace(
  prompt_template,
  'Create a premium lifestyle interior image placing',
  E'CRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product from the reference image must be placed naturally inside a fully furnished, realistic bedroom. The room must contain a balanced mix of complementary furniture and decor appropriate to the scene:\n• If the product is a BED or HEADBOARD: add matching nightstands on both sides with lamps, a textured area rug beside/under the bed, a throw or blanket layered on the bed, wall art or a mirror above, and optionally a bench or chair at the foot.\n• If the product is a NIGHTSTAND or SIDE TABLE: show it beside a properly made bed with bedding, a lamp on top, and the rest of the bedroom visible (rug, art, opposite nightstand).\n• If the product is a DRESSER or CHEST: place it against the wall in a bedroom that also contains a fully styled bed with nightstands, rug, and lighting in the background or mid-ground.\n• If the product is a WARDROBE or CLOSET: position it along a wall with a full bedroom arrangement (bed, nightstands, rug, seating) visible in the composition.\n• If the product is a CHAIR, BENCH, or OTTOMAN: show it at the foot of the bed or in a reading corner, with the full bedroom (bed, nightstands, rug, lighting) as context.\n• If the product is a RUG: lay it beside or under the bed with the full bedroom suite (bed, nightstands, lamps, art) visible above.\n• If the product is a LAMP or LIGHTING FIXTURE: show it on a nightstand or as a floor lamp beside seating, with the complete bedroom visible.\nThe scene must look like a real inhabited, decorated bedroom — never an isolated product in an empty room. Every complementary piece must match the room''s aesthetic and color palette.\n\nCreate a premium lifestyle interior image placing'
)
WHERE scene_id IN (
  'furniture-lifestyle-linen-cloud-suite',
  'furniture-lifestyle-parisian-pied-a-terre',
  'furniture-lifestyle-coastal-dawn-retreat',
  'furniture-lifestyle-warm-walnut-sanctuary',
  'furniture-lifestyle-scandi-hygge-nest',
  'furniture-lifestyle-terracotta-linen-villa',
  'furniture-lifestyle-japandi-sleep-temple',
  'furniture-lifestyle-hamptons-morning-suite',
  'furniture-lifestyle-milanese-atelier-bedroom',
  'furniture-lifestyle-desert-stone-retreat',
  'furniture-lifestyle-skyline-penthouse-bedroom',
  'furniture-lifestyle-garden-conservatory-bedroom'
);

-- 2. Fix "visual hero" / "visually dominant" phrasing
UPDATE product_image_scenes
SET prompt_template = regexp_replace(
  prompt_template,
  'The furniture must remain [^.]+\.',
  'The product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded in the space.'
)
WHERE scene_id IN (
  'furniture-lifestyle-linen-cloud-suite',
  'furniture-lifestyle-parisian-pied-a-terre',
  'furniture-lifestyle-coastal-dawn-retreat',
  'furniture-lifestyle-warm-walnut-sanctuary',
  'furniture-lifestyle-scandi-hygge-nest',
  'furniture-lifestyle-terracotta-linen-villa',
  'furniture-lifestyle-japandi-sleep-temple',
  'furniture-lifestyle-hamptons-morning-suite',
  'furniture-lifestyle-milanese-atelier-bedroom',
  'furniture-lifestyle-desert-stone-retreat',
  'furniture-lifestyle-skyline-penthouse-bedroom',
  'furniture-lifestyle-garden-conservatory-bedroom'
);

-- 3. Insert 6 new trending bedroom scenes

INSERT INTO product_image_scenes (scene_id, title, description, scene_type, category_collection, sub_category, sort_order, is_active, prompt_template, trigger_blocks, filter_tags)
VALUES
('furniture-lifestyle-quiet-luxury-moody-suite', 'Quiet Luxury Moody Suite', 'Dark chocolate and warm amber bedroom with fluted wood paneling', 'lifestyle', 'furniture', 'Bedroom', 154, true,
E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nCRITICAL — PROPORTIONAL SCALE RULE: Calculate the product''s real-world size as a fraction of the room width. A 180cm bed in a 5m-wide room occupies roughly 36% of the wall. A 60cm nightstand spans 12% of a 5m wall. Use these proportions strictly. HUMAN SCALE ANCHOR: Imagine a 175cm adult lying on the bed or standing beside the product — the product must look dimensionally correct. ARCHITECTURAL CALIBRATION: The standard interior door (210cm × 90cm) is your ruler. NEVER let the product fill more than 45% of the visible wall unless its real dimensions require it.\n\nCRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product from the reference image must be placed naturally inside a fully furnished, realistic bedroom. The room must contain a balanced mix of complementary furniture and decor:\n• If the product is a BED or HEADBOARD: add matching nightstands on both sides with lamps, a textured area rug, a throw, wall art or mirror, and optionally a bench or chair at the foot.\n• If the product is a NIGHTSTAND, DRESSER, CHAIR, BENCH, RUG, or LAMP: integrate it into a complete bedroom with all expected furnishings visible.\nThe scene must look like a real inhabited, decorated bedroom — never an isolated product in an empty room.\n\nCreate a premium lifestyle interior image placing {{productName}} in a moody quiet-luxury bedroom (approximately 5m × 4.5m, 2.8m ceiling) with dark-stained wide-plank walnut flooring. Feature wall behind the bed in vertical fluted dark oak paneling (warm chocolate brown). Remaining walls in deep warm taupe limewash plaster. Two tall windows (2m) with heavy dark linen curtains in charcoal, partially drawn.\n\nSTYLED INTERIOR DETAILS: Rich chocolate velvet bedding layered with a cashmere throw in warm amber. Two sculptural nightstands in dark bronze with integrated reading lamps emitting warm pools of light. A large abstract artwork in muted earth tones (burnt sienna, raw umber) above the headboard. A deep boucle armchair in warm taupe at the foot of the bed beside a slim brass floor lamp. A thick hand-knotted wool rug in warm charcoal beside the bed. A dark ceramic vase with dried eucalyptus on the dresser.\n\nThe product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded in the space. Color palette: dark chocolate, warm amber, deep taupe, bronze, charcoal. Rich, enveloping, whisper-quiet luxury.\n\nLighting: warm amber accent lighting from nightstand lamps and floor lamp. Low, intimate, golden. Deep shadows in corners creating depth.\n\nShot with 35mm lens, eye-level, centered composition. Quiet luxury editorial — Cereal Magazine aesthetic. Photorealistic. No text.',
'{}', '{}'),

('furniture-lifestyle-curved-plaster-grotto', 'Curved Plaster Grotto', 'Organic arched plaster walls with Mediterranean warmth', 'lifestyle', 'furniture', 'Bedroom', 155, true,
E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nCRITICAL — PROPORTIONAL SCALE RULE: Calculate the product''s real-world size as a fraction of the room width. A 180cm bed in a 5m-wide room occupies roughly 36% of the wall. HUMAN SCALE ANCHOR: Imagine a 175cm adult beside the product. ARCHITECTURAL CALIBRATION: The standard interior door (210cm × 90cm) is your ruler. Arched openings (240cm tall) are secondary references. NEVER let the product fill more than 45% of the visible wall.\n\nCRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product must be placed inside a fully furnished bedroom with complementary nightstands, lamps, rugs, art, and seating. The scene must look like a real inhabited, decorated bedroom.\n\nCreate a premium lifestyle interior image placing {{productName}} in a sculptural Mediterranean bedroom (approximately 5m × 4.5m, 3m ceiling) with smooth hand-troweled white lime plaster walls featuring organic curved archways and a recessed arched niche behind the bed. Polished warm cream tadelakt flooring. One large arched window (2.2m) with flowing sheer linen curtains in natural ivory.\n\nSTYLED INTERIOR DETAILS: Crisp white linen bedding with a hand-woven cream cotton blanket folded at the foot. Two curved plaster built-in nightstand shelves flanking the bed, each with a handmade ceramic oil lamp. A round recessed wall niche above the bed holding a single terracotta vessel. A low woven seagrass bench at the foot of the bed with a folded linen throw. A thick natural jute rug beneath the bed. A small olive tree in a weathered clay pot beside the window. Subtle dried palm frond arrangement on one nightstand.\n\nThe product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded. Color palette: white plaster, warm cream, natural clay, ivory linen, soft terracotta. Organic, cave-like serenity.\n\nLighting: warm Mediterranean morning light through the arched window. Soft, diffused, golden. Gentle shadows from curved architecture.\n\nShot with 35mm lens, eye-level, slightly off-center. Organic Mediterranean editorial — Openhouse Magazine aesthetic. Photorealistic. No text.',
'{}', '{}'),

('furniture-lifestyle-moss-green-velvet-cocoon', 'Moss Green Velvet Cocoon', 'Deep forest green walls with rich velvet and biophilic accents', 'lifestyle', 'furniture', 'Bedroom', 156, true,
E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nCRITICAL — PROPORTIONAL SCALE RULE: Calculate the product''s real-world size as a fraction of the room width. A 180cm bed in a 5m-wide room occupies roughly 36% of the wall. HUMAN SCALE ANCHOR: Imagine a 175cm adult beside the product. ARCHITECTURAL CALIBRATION: Standard interior door (210cm × 90cm) is your ruler. NEVER let the product fill more than 45% of the visible wall.\n\nCRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product must be placed inside a fully furnished bedroom with complementary nightstands, lamps, rugs, art, and seating. The scene must look like a real inhabited, decorated bedroom.\n\nCreate a premium lifestyle interior image placing {{productName}} in a cocoon-like biophilic bedroom (approximately 5m × 4.5m, 2.8m ceiling) with dark-stained herringbone oak flooring. Walls painted in deep moss green (matte, rich forest tone). Ceiling in warm off-white creating contrast. Two tall windows (2.1m) with thick olive-toned linen curtains and brass curtain rods.\n\nSTYLED INTERIOR DETAILS: Deep emerald velvet bedding layered with a chunky oatmeal knit throw. Moss green velvet Euro shams. Two warm walnut nightstands with brass pulls, each holding a mushroom-shaped ceramic lamp in warm white. A large botanical print (fern study, vintage style) in a thin brass frame above the headboard. A low leather-and-walnut reading chair in cognac beside a slim brass floor lamp in the corner. A deep-pile wool rug in warm sage beneath the bed. A trailing pothos plant on the dresser, a small stack of coffee-table books on one nightstand. A ceramic incense holder on the other.\n\nThe product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded. Color palette: deep moss green, warm walnut, cognac leather, brass, oatmeal. Moody, botanical, deeply cozy.\n\nLighting: warm filtered light through curtains, accent warmth from ceramic lamps. Intimate, golden-green ambient glow.\n\nShot with 35mm lens, eye-level, balanced composition. Biophilic luxury editorial — The Kinfolk Home aesthetic. Photorealistic. No text.',
'{}', '{}'),

('furniture-lifestyle-raw-earth-wabi-sabi', 'Raw Earth Wabi-Sabi Room', 'Imperfect plaster textures with reclaimed wood and organic calm', 'lifestyle', 'furniture', 'Bedroom', 157, true,
E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nCRITICAL — PROPORTIONAL SCALE RULE: Calculate the product''s real-world size as a fraction of the room width. A 180cm bed in a 4.5m-wide room occupies roughly 40% of the wall. HUMAN SCALE ANCHOR: Imagine a 175cm adult beside the product. ARCHITECTURAL CALIBRATION: Standard interior door (210cm × 90cm) is your ruler. NEVER let the product fill more than 45% of the visible wall.\n\nCRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product must be placed inside a fully furnished bedroom with complementary nightstands, lamps, rugs, art, and seating. The scene must look like a real inhabited, decorated bedroom.\n\nCreate a premium lifestyle interior image placing {{productName}} in a serene wabi-sabi bedroom (approximately 4.5m × 4m, 2.7m ceiling) with reclaimed wide-plank timber flooring showing natural knots and gentle patina. Walls in raw clay-toned plaster with deliberate imperfections — visible trowel marks, subtle color variation from warm sand to pale terracotta. One window (1.8m) with a simple unbleached cotton curtain panel.\n\nSTYLED INTERIOR DETAILS: Undyed linen bedding in natural flax with visible weave texture. A single washed linen duvet in warm mushroom. Two mismatched vintage wooden stools serving as nightstands — one with a handmade stoneware oil lamp, the other with a small ceramic bowl holding dried wildflowers. An irregularly shaped handmade ceramic wall sculpture (40cm) above the bed. A low wooden bench at the foot with a folded indigo-dyed textile. A hand-knotted jute rug with uneven edges beside the bed. A single branch of dried cotton stems in a rough clay vessel on the floor.\n\nThe product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded. Color palette: raw clay, warm sand, mushroom, natural flax, weathered wood. Imperfect, honest, deeply calm.\n\nLighting: soft natural light from the single window. Warm, even, slightly diffused. No artificial light visible — pure natural ambiance.\n\nShot with 35mm lens, eye-level, asymmetric composition. Wabi-sabi editorial — Axel Vervoordt aesthetic. Photorealistic. No text.',
'{}', '{}'),

('furniture-lifestyle-warm-minimalist-loft-bedroom', 'Warm Minimalist Loft', 'Open concrete and linen bedroom with warm minimalism', 'lifestyle', 'furniture', 'Bedroom', 158, true,
E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nCRITICAL — PROPORTIONAL SCALE RULE: Calculate the product''s real-world size as a fraction of the room width. A 180cm bed in a 5.5m-wide room occupies roughly 33% of the wall. HUMAN SCALE ANCHOR: Imagine a 175cm adult beside the product. ARCHITECTURAL CALIBRATION: Standard interior door (210cm × 90cm) is your ruler. Industrial windows (280cm tall) are secondary references. NEVER let the product fill more than 45% of the visible wall.\n\nCRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product must be placed inside a fully furnished bedroom with complementary nightstands, lamps, rugs, art, and seating. The scene must look like a real inhabited, decorated bedroom.\n\nCreate a premium lifestyle interior image placing {{productName}} in a warm minimalist loft bedroom (approximately 5.5m × 5m, 3.5m ceiling) with polished concrete flooring in warm gray with subtle aggregate visible. Smooth white-washed brick on one feature wall. Remaining walls in warm putty-toned micro-cement. Large industrial steel-framed windows (2.8m tall) with slim black mullions, no curtains.\n\nSTYLED INTERIOR DETAILS: Warm stone-washed linen bedding in sand with a lightweight cream waffle blanket. Two identical slim concrete-and-oak nightstands with matte black task lamps. A large-scale minimal line drawing in a thin black frame leaning against the brick wall above the bed. A low-profile oak bench at the foot of the bed with a folded cashmere throw in warm camel. A deep hand-tufted wool rug in warm cream beneath the bed. A tall fiddle-leaf fig in a matte black ceramic planter in the corner. A single book and ceramic cup on one nightstand.\n\nThe product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded. Color palette: warm gray concrete, sand, putty, warm cream, black accents. Warm, intentional, architecturally honest.\n\nLighting: abundant natural light from industrial windows. Clean, bright, warm afternoon tone. No harsh shadows — even illumination with slight warmth.\n\nShot with 28mm lens, eye-level, wide composition showing ceiling height. Warm minimalist editorial — Kinfolk aesthetic. Photorealistic. No text.',
'{}', '{}'),

('furniture-lifestyle-art-deco-revival-boudoir', 'Art Deco Revival Boudoir', 'Emerald and brass geometric bedroom with neo-deco glamour', 'lifestyle', 'furniture', 'Bedroom', 159, true,
E'Use [PRODUCT IMAGE] as the exact source of truth for {{productName}}, preserving exact structure, scale, finish, proportions, and all product details.\n\nCRITICAL — PROPORTIONAL SCALE RULE: Calculate the product''s real-world size as a fraction of the room width. A 180cm bed in a 5m-wide room occupies roughly 36% of the wall. HUMAN SCALE ANCHOR: Imagine a 175cm adult beside the product. ARCHITECTURAL CALIBRATION: Standard interior door (210cm × 90cm) is your ruler. Tall paneled doors (260cm) are secondary references. NEVER let the product fill more than 45% of the visible wall.\n\nCRITICAL — COMPLETE INTERIOR COMPOSITION: This is a full room interior photograph, NOT a product-only shot. The product must be placed inside a fully furnished bedroom with complementary nightstands, lamps, rugs, art, and seating. The scene must look like a real inhabited, decorated bedroom.\n\nCreate a premium lifestyle interior image placing {{productName}} in a neo-Art Deco bedroom (approximately 5m × 4.5m, 3m ceiling) with dark chevron-pattern parquet flooring in rich espresso. Feature wall behind the bed upholstered in deep emerald green fluted velvet paneling. Remaining walls in warm cream with subtle geometric Art Deco moulding patterns. Crown moulding with a thin brass inlay line. Tall paneled double doors (2.6m) in dark lacquered wood.\n\nSTYLED INTERIOR DETAILS: Emerald and ivory silk bedding with a geometric quilted throw in warm gold. Two symmetrical demi-lune nightstands in dark lacquer with brass legs, each holding a sculptural brass table lamp with a black shade. A large sunburst mirror in brushed brass (80cm) above the headboard. A curved velvet bench in deep teal at the foot of the bed. A deep geometric-patterned wool rug in emerald, cream, and gold. A crystal decanter set on a brass tray on the dresser. A tall brass torchiere floor lamp in the corner.\n\nThe product must be the primary focal point within a fully furnished, balanced interior — correctly scaled and grounded. Color palette: deep emerald, warm gold/brass, dark espresso, warm cream, touches of teal. Glamorous, bold, neo-deco elegance.\n\nLighting: warm golden ambient light from brass lamps and torchiere. Rich, dramatic, theatrical. Subtle shadow play from geometric mouldings.\n\nShot with 35mm lens, eye-level, symmetrical composition. Art Deco revival editorial — AD Italia aesthetic. Photorealistic. No text.',
'{}', '{}');