UPDATE public.workflows
SET generation_config = jsonb_set(
  jsonb_set(
    generation_config,
    '{variation_strategy,variations}',
    $JSON$[
  {"label":"Golden Hour Selfie","category":"Everyday Moments","instruction":"Outdoor magic-hour selfie on a clean rooftop or open balcony. Warm, glowing rim light from a low sun on the subject and product. Minimal concrete or stone backdrop with soft greenery in the distance — no clutter, no signage, no busy props. Quiet luxury palette: warm cream, sand, sun-faded terracotta. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/scratch-uploads/workflow-variations/selfie-ugc-set/1775140260364-qpef6v.jpg","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Coffee Shop / Brunch","category":"Everyday Moments","instruction":"Quiet specialty coffee shop. The subject is seated at a polished marble or solid oak table with a single ceramic flat-white cup. Soft window daylight from one side. Tidy, considered surroundings — uncluttered table, blurred neutral interior. Quiet luxury palette: bone, oat, espresso brown. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-1.png?t=1771156585929","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Car Selfie","category":"Everyday Moments","instruction":"Inside a modern car with cream or tan leather interior. Soft daylight pours through the windshield. Seatbelt visible across the chest. Clean dash, no clutter, no phone mounts, no visible branding. Quiet luxury palette: tan leather, brushed metal, cream. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-2.png?t=1771156609101","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Walking Street Style","category":"Everyday Moments","instruction":"Quiet European-style street with neutral architecture (limestone, pale render, simple shutters). Soft overcast daylight, minimal foot traffic, no visible signage or logos. The subject walks with confident, relaxed posture. Quiet luxury palette: stone, taupe, off-white. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-3.png?t=1771156633488","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Gym / Workout","category":"Everyday Moments","instruction":"Boutique studio gym — light wood floors, white walls, a few green plants, soft daylight. No messy lockers, no piles of weights, no neon signage. Post-workout glow on the subject. Quiet luxury palette: warm white, oak, sage. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-4.png?t=1771156654087","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Morning Routine / GRWM","category":"At Home","instruction":"Bright, minimalist bathroom or vanity. Marble or stone counter with only a few curated essentials (one ceramic dish, a single glass, a folded linen towel). Soft, even morning light from a side window. Surfaces are clean and uncluttered. Quiet luxury palette: white marble, brushed nickel, soft greige. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-5.png?t=1771156716785","aspect_ratio":"4:5"},
  {"label":"Bedroom Outfit Check","category":"At Home","instruction":"Tidy neutral bedroom with linen bedding and a single curated outfit visible. Soft daylight from a sheer-curtained window. Clear floor, no laundry, no visual clutter. Full-length or three-quarter mirror selfie composition. Quiet luxury palette: ivory linen, oak, warm white. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-6.png?t=1771156744744","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Couch / Netflix Chill","category":"At Home","instruction":"Relaxed pose on a linen-upholstered couch with a soft neutral throw and one or two cushions. Warm lamp light, evening mood, no TV glare, no fairy lights. Minimal styling, considered and calm. Quiet luxury palette: oat linen, caramel, warm grey. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-7.png?t=1771156766248","aspect_ratio":"4:5"},
  {"label":"Kitchen Counter","category":"At Home","instruction":"Standing at or leaning on a stone or solid oak kitchen counter. Calm morning light from a window. A single ceramic mug and a small bowl of fresh fruit are the only props. Surfaces are spotless and uncluttered, no appliances on display. Quiet luxury palette: travertine, oak, warm white. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-8.png?t=1771156821352","aspect_ratio":"4:5","wearable_only":true},
  {"label":"Unboxing Excitement","category":"Content Creator","instruction":"Tidy desk with a branded box placed on a linen surface, tissue paper folded neatly to one side. Soft, even daylight from a side window. The subject reveals the product to camera with calm, genuine delight — no exaggerated expression, no clutter. Quiet luxury palette: bone, kraft paper, soft taupe. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-9.png?t=1771156842568","aspect_ratio":"4:5","holdable_only":true},
  {"label":"Product Holding in Hand","category":"Content Creator","instruction":"The subject holds the product intentionally at chest level, framed against a neutral indoor backdrop (soft plaster wall or oak panel). Even diffused daylight, calm posture, eyes warm and direct. The product is the clear focal point. Quiet luxury palette: warm white, sand, soft shadow. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-11.png?t=1771156916839","aspect_ratio":"4:5","holdable_only":true},
  {"label":"Hands-Only Demo","category":"Close-up","instruction":"ONLY hands visible in frame — NO face, NO body above the wrists. Hands rest on a linen or stone surface, demonstrating or holding the product. Soft top-down daylight, sharp detail on product and hands. Uncluttered surface, the product is the hero. Quiet luxury palette: linen, travertine, warm shadow. The subject is {PRODUCT_INTERACTION}.","preview_url":"https://azwiljtrbtaupofwmpzb.supabase.co/storage/v1/object/public/workflow-previews/3b54d43a-a03a-49a6-a64e-bf2dd999abc8/scene-15.png?t=1771157041364","aspect_ratio":"4:5","holdable_only":true}
]$JSON$::jsonb
  ),
  '{negative_prompt_additions}',
  to_jsonb(
    COALESCE(generation_config->>'negative_prompt_additions', '') ||
    CASE WHEN COALESCE(generation_config->>'negative_prompt_additions', '') = '' THEN '' ELSE ', ' END ||
    'garment held up to camera when wearing was selected, product on hanger, product on mannequin, clutter, messy table, dirty surfaces, neon colors, harsh studio shadows, plastic-looking props, busy patterns, kitsch decor, multiple unrelated brands visible'
  )
)
WHERE slug = 'selfie-ugc-set';