
ALTER TABLE public.feedback
  ADD COLUMN IF NOT EXISTS workflow TEXT,
  ADD COLUMN IF NOT EXISTS trigger_type TEXT,
  ADD COLUMN IF NOT EXISTS primary_answer TEXT,
  ADD COLUMN IF NOT EXISTS reasons TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS question_key TEXT,
  ADD COLUMN IF NOT EXISTS result_id UUID,
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS user_plan TEXT,
  ADD COLUMN IF NOT EXISTS priority TEXT DEFAULT 'none';
